.catalog:
  name: "Rancher CIFS"
  version: "0.2.2"
  description: |
    Docker volume plugin for CIFS
  minimum_rancher_version: v1.4.0-rc1
  questions:
  - variable: "CIFS_SERVER"
    description: "IP or hostname of the CIFS Server"
    label: "CIFS Server"
    required: true
    type: "string"
  - variable: "MOUNT_DIR"
    label: "Mount Directory"
    description: "The directory on the CIFS server to mount"
    type: "string"
    required: true
  - variable: "MOUNT_OPTS"
    label: "Mount Options"
    description: "Comma delimited list of mount options.  For example: 'uid=1100,gid=1100'"
    type: "string"
  - variable: "RANCHER_DEBUG"
    label: "Debug Mode"
    type: "enum"
    description: "Enable or disable verbose logging"
    default: false
    options:
    - true
    - false
cifs-driver:
  storage_driver:
    name: rancher-cifs
    scope: environment
    volume_access_mode: multiHostRW
